/**
 * Google Sheets Service
 * Quản lý lưu trữ dữ liệu trên Google Sheets — External Database
 * File: "SmartLife - Dữ Liệu Ghi Chú & Lưu Trữ Cá Nhân"
 */

import { googleApiFetch, getValidGoogleToken } from './googleAuthTokenManager';

const SHEETS_API_BASE = 'https://sheets.googleapis.com/v4/spreadsheets';
const DRIVE_API_BASE = 'https://www.googleapis.com/drive/v3/files';

const SPREADSHEET_TITLE = 'SmartLife - Dữ Liệu Ghi Chú & Lưu Trữ Cá Nhân';

// Storage keys
const STORAGE_KEYS = {
  SPREADSHEET_ID: 'smartlife_gsheets_spreadsheet_id',
  LAST_SYNC: 'smartlife_gsheets_last_sync',
  AUTO_SYNC: 'smartlife_gsheets_auto_sync',
};

// Tab names
const TAB_NAMES = {
  NOTE_ARCHIVES: 'Note Archives',
  QUICK_NOTES: 'Quick Notes',
  AI_SUMMARIES: 'AI Summaries',
};

// Headers cho mỗi tab
const TAB_HEADERS: Record<string, string[]> = {
  [TAB_NAMES.NOTE_ARCHIVES]: ['ID', 'Ngày tạo', 'Tiêu đề', 'Nhãn (Labels)', 'Nội dung chi tiết', 'Ghim', 'Cập nhật cuối'],
  [TAB_NAMES.QUICK_NOTES]: ['ID', 'Timestamp', 'Nội dung', 'Loại'],
  [TAB_NAMES.AI_SUMMARIES]: ['ID', 'Ngày', 'Loại báo cáo', 'Nội dung', 'Generated by'],
};

// ────────────────────────────────────────
// Settings
// ────────────────────────────────────────

export const isSheetsConnected = (): boolean => {
  return getValidGoogleToken() !== null;
};

export const getStoredSpreadsheetId = (): string | null => {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(STORAGE_KEYS.SPREADSHEET_ID);
};

export const isSheetsAutoSyncEnabled = (): boolean => {
  if (typeof window === 'undefined') return false;
  const stored = localStorage.getItem(STORAGE_KEYS.AUTO_SYNC);
  return stored === 'true';
};

export const setSheetsAutoSync = (enabled: boolean): void => {
  if (typeof window === 'undefined') return;
  localStorage.setItem(STORAGE_KEYS.AUTO_SYNC, enabled ? 'true' : 'false');
};

export const getLastSheetsSync = (): string | null => {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(STORAGE_KEYS.LAST_SYNC);
};

// ────────────────────────────────────────
// Find or Create Spreadsheet
// ────────────────────────────────────────

/**
 * Tìm file Spreadsheet "SmartLife - Dữ Liệu Ghi Chú & Lưu Trữ Cá Nhân" trên Drive
 * Nếu chưa có → tạo mới với 3 tabs chuẩn hóa
 */
export const findOrCreateSpreadsheet = async (): Promise<string> => {
  // 1. Check cache first
  const cachedId = getStoredSpreadsheetId();
  if (cachedId) {
    // Verify it still exists
    try {
      const response = await googleApiFetch(`${SHEETS_API_BASE}/${cachedId}?fields=spreadsheetId`);
      if (response.ok) return cachedId;
    } catch {
      // Cached ID is invalid, search again
      localStorage.removeItem(STORAGE_KEYS.SPREADSHEET_ID);
    }
  }

  // 2. Search for existing file on Drive (safely wrapped in try/catch)
  try {
    const searchQuery = `name='${SPREADSHEET_TITLE}' and mimeType='application/vnd.google-apps.spreadsheet' and trashed=false`;
    const searchResponse = await googleApiFetch(
      `${DRIVE_API_BASE}?q=${encodeURIComponent(searchQuery)}&fields=files(id,name)&pageSize=1`
    );

    if (searchResponse.ok) {
      const searchData = await searchResponse.json();
      if (searchData.files && searchData.files.length > 0) {
        const spreadsheetId = searchData.files[0].id;
        localStorage.setItem(STORAGE_KEYS.SPREADSHEET_ID, spreadsheetId);
        return spreadsheetId;
      }
    }
  } catch (driveErr) {
    console.warn('[GoogleSheets] Drive search notice (proceeding to create via Sheets API):', driveErr);
  }

  // 3. Create new spreadsheet with 3 clean tabs
  const createBody = {
    properties: {
      title: SPREADSHEET_TITLE,
    },
    sheets: [
      { properties: { title: TAB_NAMES.NOTE_ARCHIVES } },
      { properties: { title: TAB_NAMES.QUICK_NOTES } },
      { properties: { title: TAB_NAMES.AI_SUMMARIES } },
    ],
  };

  const createResponse = await googleApiFetch(SHEETS_API_BASE, {
    method: 'POST',
    body: JSON.stringify(createBody),
  });

  if (!createResponse.ok) {
    const err = await createResponse.text();
    throw new Error(`Không thể tạo Spreadsheet (${createResponse.status}): ${err}`);
  }

  const createData = await createResponse.json();
  const newId = createData.spreadsheetId;
  localStorage.setItem(STORAGE_KEYS.SPREADSHEET_ID, newId);

  // Initialize header rows for each tab in parallel
  try {
    await Promise.all([
      appendSheetData(newId, `'${TAB_NAMES.NOTE_ARCHIVES}'!A1`, [TAB_HEADERS[TAB_NAMES.NOTE_ARCHIVES]]),
      appendSheetData(newId, `'${TAB_NAMES.QUICK_NOTES}'!A1`, [TAB_HEADERS[TAB_NAMES.QUICK_NOTES]]),
      appendSheetData(newId, `'${TAB_NAMES.AI_SUMMARIES}'!A1`, [TAB_HEADERS[TAB_NAMES.AI_SUMMARIES]]),
    ]);
  } catch (headerErr) {
    console.warn('[GoogleSheets] Error writing initial headers:', headerErr);
  }

  console.info(`[GoogleSheets] Created new spreadsheet: ${newId}`);
  return newId;
};

// ────────────────────────────────────────
// Read / Write Data
// ────────────────────────────────────────

/**
 * Đọc dữ liệu từ 1 tab (range)
 */
export const readSheetData = async (
  spreadsheetId: string,
  range: string
): Promise<string[][]> => {
  const response = await googleApiFetch(
    `${SHEETS_API_BASE}/${spreadsheetId}/values/${encodeURIComponent(range)}`
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Sheets API readData error ${response.status}: ${err}`);
  }

  const data = await response.json();
  return data.values || [];
};

/**
 * Append dữ liệu vào cuối tab
 */
export const appendSheetData = async (
  spreadsheetId: string,
  range: string,
  values: string[][]
): Promise<void> => {
  const response = await googleApiFetch(
    `${SHEETS_API_BASE}/${spreadsheetId}/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,
    {
      method: 'POST',
      body: JSON.stringify({ values }),
    }
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Sheets API appendData error ${response.status}: ${err}`);
  }
};

/**
 * Update dữ liệu tại vị trí cụ thể
 */
export const updateSheetData = async (
  spreadsheetId: string,
  range: string,
  values: string[][]
): Promise<void> => {
  const response = await googleApiFetch(
    `${SHEETS_API_BASE}/${spreadsheetId}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,
    {
      method: 'PUT',
      body: JSON.stringify({ values }),
    }
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Sheets API updateData error ${response.status}: ${err}`);
  }
};

// ────────────────────────────────────────
// High-Level Note Operations
// ────────────────────────────────────────

/**
 * Sync một ghi chú vào tab "Note Archives"
 */
export const syncNoteToSheets = async (note: {
  id: string;
  title: string;
  content: string;
  labels?: string[];
  is_pinned?: boolean;
  created_at?: string;
  updated_at?: string;
}): Promise<void> => {
  const spreadsheetId = await findOrCreateSpreadsheet();

  // Check if note already exists (by ID in column A)
  const existingData = await readSheetData(spreadsheetId, `'${TAB_NAMES.NOTE_ARCHIVES}'!A:A`);
  const rowIndex = existingData.findIndex(row => row[0] === note.id);

  const row = [
    note.id,
    note.created_at || new Date().toISOString().slice(0, 10),
    note.title,
    (note.labels || []).join(', '),
    note.content,
    note.is_pinned ? 'TRUE' : 'FALSE',
    note.updated_at || new Date().toISOString().slice(0, 16).replace('T', ' '),
  ];

  if (rowIndex >= 0) {
    // Update existing row (rowIndex + 1 because Sheets is 1-indexed)
    await updateSheetData(
      spreadsheetId,
      `'${TAB_NAMES.NOTE_ARCHIVES}'!A${rowIndex + 1}:G${rowIndex + 1}`,
      [row]
    );
  } else {
    // Append new row
    await appendSheetData(spreadsheetId, `'${TAB_NAMES.NOTE_ARCHIVES}'!A:G`, [row]);
  }

  localStorage.setItem(STORAGE_KEYS.LAST_SYNC, new Date().toISOString());
};

/**
 * Sync quick note vào tab "Quick Notes"
 */
export const syncQuickNoteToSheets = async (note: {
  id: string;
  content: string;
  type?: string;
}): Promise<void> => {
  const spreadsheetId = await findOrCreateSpreadsheet();

  const row = [
    note.id,
    new Date().toISOString().slice(0, 19).replace('T', ' '),
    note.content,
    note.type || 'quick_note',
  ];

  await appendSheetData(spreadsheetId, `'${TAB_NAMES.QUICK_NOTES}'!A:D`, [row]);
  localStorage.setItem(STORAGE_KEYS.LAST_SYNC, new Date().toISOString());
};

/**
 * Lưu AI Summary vào tab "AI Summaries"
 */
export const syncAISummaryToSheets = async (summary: {
  id: string;
  type: string;
  content: string;
}): Promise<void> => {
  const spreadsheetId = await findOrCreateSpreadsheet();

  const row = [
    summary.id,
    new Date().toISOString().slice(0, 10),
    summary.type,
    summary.content,
    'Gemini AI',
  ];

  await appendSheetData(spreadsheetId, `'${TAB_NAMES.AI_SUMMARIES}'!A:E`, [row]);
  localStorage.setItem(STORAGE_KEYS.LAST_SYNC, new Date().toISOString());
};

/**
 * Lấy URL mở Spreadsheet trên Google Sheets
 */
export const getSpreadsheetUrl = async (): Promise<string | null> => {
  const id = getStoredSpreadsheetId();
  if (!id) return null;
  return `https://docs.google.com/spreadsheets/d/${id}/edit`;
};

/**
 * Lấy tất cả dữ liệu từ tab Note Archives
 */
export const getAllNoteArchivesFromSheets = async (): Promise<Array<{
  id: string;
  created_at: string;
  title: string;
  labels: string;
  content: string;
  is_pinned: boolean;
  updated_at: string;
}>> => {
  const spreadsheetId = await findOrCreateSpreadsheet();
  const data = await readSheetData(spreadsheetId, `'${TAB_NAMES.NOTE_ARCHIVES}'!A2:G`);

  return data.map(row => ({
    id: row[0] || '',
    created_at: row[1] || '',
    title: row[2] || '',
    labels: row[3] || '',
    content: row[4] || '',
    is_pinned: (row[5] || '').toUpperCase() === 'TRUE',
    updated_at: row[6] || '',
  }));
};
